const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { pathToFileURL } = require('url');
const { spawn } = require('child_process');
const readline = require('readline');

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'typebreeze-worker-'));
fs.writeFileSync(path.join(root, 'tsconfig.json'), JSON.stringify({ compilerOptions: { strict: true } }));
fs.writeFileSync(path.join(root, 'types.ts'), `
export type ToastStyleType = 'normal' | 'wide';
interface ToastProps { styleType?: ToastStyleType }
type ShortHandToastProps = Omit<ToastProps, 'unused'>;
export function showSuccessToast(message: string, props?: Partial<ShortHandToastProps>) {}
export function useGeneric<const TDefaults extends Partial<ToastProps>>(defaults: TDefaults) {}
`);
fs.writeFileSync(path.join(root, 'hooks.ts'), `import { ToastStyleType } from './types';
export type Options = { toastStyle?: ToastStyleType };
export function useHook(options: Options) {}
`);
const usage = `import { useHook } from './hooks';
import { useGeneric, ToastStyleType } from './types';
useHook({ toastStyle: 'wide' });
const ordinary = 'wide';
useGeneric({ styleType: 'wide' });
declare const status: ToastStyleType;
const compared = status === 'wide';
`;
const usagePath = path.join(root, 'usage.ts');
fs.writeFileSync(usagePath, usage);
const domainPath = path.join(root, 'domain.ts');
fs.writeFileSync(domainPath, "export type DomainType = 'TestCase' | 'TestPoint';\nexport function useDomainClassTracker<T extends DomainType>(entityType: T, handler: (value: T) => void) {}\nexport function useDomainEntityTracker<T extends DomainType>(entityType: T, id: number, handler: (value: T) => void) {}\nexport function ordinary<T extends string>(value: T) {}\n");
const domainUsagePath = path.join(root, 'domain-usage.ts');
fs.writeFileSync(domainUsagePath, "import { useDomainClassTracker, useDomainEntityTracker, ordinary } from './domain';\nuseDomainClassTracker('TestCase', value => {});\nuseDomainEntityTracker('TestCase', 1, value => {});\nordinary('TestCase');\nuseDomainClassTracker<'TestCase'>('TestCase', value => {});\n");
const mappingUsagePath = path.join(root, 'domain-mappings.ts');
fs.writeFileSync(mappingUsagePath, `import { DomainType } from './domain';
type DomainMap = { [K in DomainType]: number };
const annotated: Record<DomainType, number> = { TestCase: 1, 'TestPoint': 2 };
const checked = { TestCase: 1, TestPoint: 2 } satisfies DomainMap;
const readonly: Readonly<Record<DomainType, number>> = { TestCase: 1, TestPoint: 2 };
declare function accept(value: DomainMap): void;
accept({ TestCase: 1, TestPoint: 2 });
interface Options { extraConditions?: DomainMap }
declare function useOptions(options?: Options): void;
useOptions({ extraConditions: { TestCase: 1, TestPoint: 2 } });
const ordinary: { TestCase: number; TestPoint: number } = { TestCase: 1, TestPoint: 2 };
const indexed: { [key: string]: number } = { TestCase: 1, TestPoint: 2 };
const TestCase = 1; const shorthand: DomainMap = { TestCase, TestPoint: 2 };
const methods = { TestCase() {}, TestPoint() {} } satisfies { [K in DomainType]: () => void };
`);

const child = spawn(process.execPath, [path.join(__dirname, 'worker.cjs')], { stdio: ['pipe', 'pipe', 'inherit'] });
const lines = readline.createInterface({ input: child.stdout });
const pending = new Map(); let nextId = 1;
lines.on('line', line => { const message = JSON.parse(line); const callback = pending.get(message.id); pending.delete(message.id); callback(message); });
function request(method, params) { return new Promise((resolve, reject) => { const id = nextId++; pending.set(id, message => message.error ? reject(new Error(message.error)) : resolve(message.result)); child.stdin.write(JSON.stringify({ id, method, params }) + '\n'); }); }

(async () => {
  await request('initialize', { root });
  const domainDocument = await request('documentUnions', { textDocument: { uri: pathToFileURL(domainUsagePath).href }, includeUsages: false });
  assert.equal(domainDocument.literals.length, 2);
  assert(domainDocument.literals.every(item => item.kind === 'usage' && item.contextualTypeName === 'DomainType' && item.domain.uri.endsWith('/domain.ts')));
  for (const line of [1, 2]) {
    const member = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(domainUsagePath).href }, position: { line, character: 25 } });
    assert.equal(member.currentValue, 'TestCase');
    assert.deepEqual(member.assignableMembers.map(item => item.value), ['TestCase', 'TestPoint']);
  }
  const domainLocations = await request('navigationTargets', { textDocument: { uri: pathToFileURL(domainPath).href }, position: { line: 0, character: 28 } });
  assert.equal(domainLocations.length, 7);
  const domainDeclarations = await request('documentUnions', { textDocument: { uri: pathToFileURL(domainPath).href } });
  assert.equal(domainDeclarations.literals.find(item => item.currentValue === 'TestCase').usageLocations.length, 7);
  assert.equal(domainDeclarations.literals.find(item => item.currentValue === 'TestPoint').usageLocations.length, 6);
  const mappingDocument = await request('documentUnions', { textDocument: { uri: pathToFileURL(mappingUsagePath).href }, includeUsages: false });
  assert.equal(mappingDocument.literals.length, 11);
  assert(mappingDocument.literals.every(item => item.kind === 'usage' && item.contextualTypeName === 'DomainType'));
  const mappingKey = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(mappingUsagePath).href }, position: { line: 2, character: 55 } });
  assert.equal(mappingKey.currentValue, 'TestCase');
  assert(mappingKey.domain.uri.endsWith('/domain.ts'));
  const mappingNavigation = await request('navigationTargets', { textDocument: { uri: pathToFileURL(mappingUsagePath).href }, position: { line: 2, character: 55 } });
  assert.equal(mappingNavigation.length, 1); assert(mappingNavigation[0].uri.endsWith('/domain.ts'));
  const mappingRename = await request('renamePlan', { textDocument: { uri: pathToFileURL(mappingUsagePath).href }, position: { line: 2, character: 55 }, newValue: 'Test Case' });
  assert(mappingRename.targets.some(target => target.expectedText === 'TestCase' && target.newText === "'Test Case'"));
  assert(mappingRename.targets.some(target => target.expectedText === "'TestCase'" && target.newText === "'Test Case'"));
  const identifierRename = await request('renamePlan', { textDocument: { uri: pathToFileURL(mappingUsagePath).href }, position: { line: 2, character: 55 }, newValue: 'Scenario' });
  assert(identifierRename.targets.some(target => target.expectedText === 'TestCase' && target.newText === 'Scenario'));
  const declarationHover = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(path.join(root, 'types.ts')).href }, position: { line: 1, character: 46 } });
  assert.equal(declarationHover.kind, 'declaration');
  assert.equal(declarationHover.currentValue, 'wide');
  assert.equal(declarationHover.contextualTypeName, 'ToastStyleType');
  const quickDocument = await request('documentUnions', { textDocument: { uri: pathToFileURL(path.join(root, 'types.ts')).href }, includeUsages: false, clientVersion: 1 });
  assert.equal(quickDocument.clientVersion, 1);
  assert.equal(quickDocument.literals.length, 2);
  assert(quickDocument.literals.every(item => item.kind === 'declaration' && item.hasUsages === undefined && item.usageLocations === undefined));
  const target = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 2, character: 25 } });
  assert.equal(target.currentValue, 'wide');
  assert.equal(target.contextualTypeName, 'ToastStyleType');
  assert.deepEqual(target.assignableMembers.map(member => member.value), ['normal', 'wide']);
  assert(target.domain.uri.endsWith('/types.ts'));
  const toDeclaration = await request('navigationTargets', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 2, character: 25 } });
  assert.equal(toDeclaration.length, 1); assert(toDeclaration[0].uri.endsWith('/types.ts')); assert.equal(toDeclaration[0].range.start.line, 1);
  const fromDeclaration = await request('navigationTargets', { textDocument: { uri: pathToFileURL(path.join(root, 'types.ts')).href }, position: { line: 1, character: 46 } });
  assert.equal(fromDeclaration.length, 3); assert(fromDeclaration.every(location => location.uri.endsWith('/usage.ts')));
  const genericTarget = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 4, character: 27 } });
  assert.equal(genericTarget.contextualTypeName, 'ToastStyleType');
  const comparisonTarget = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 6, character: 29 } });
  assert.equal(comparisonTarget.contextualTypeName, 'ToastStyleType');
  const rename = await request('renamePlan', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 2, character: 25 }, newValue: 'expanded' });
  assert.equal(rename.oldValue, 'wide');
  assert.equal(rename.targets.length, 4);
  assert(rename.targets.some(target => target.uri.endsWith('/types.ts')));
  assert(rename.targets.some(target => target.uri.endsWith('/usage.ts') && target.expectedText === "'wide'"));
  assert(rename.targets.every(target => target.newText === "'expanded'"));
  const duplicateRename = await request('renamePlan', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 2, character: 25 }, newValue: 'normal' });
  assert.equal(duplicateRename, null);
  const declarationRename = await request('renamePlan', { textDocument: { uri: pathToFileURL(path.join(root, 'types.ts')).href }, position: { line: 1, character: 46 }, newValue: 'expanded' });
  assert.equal(declarationRename.targets.length, 4);
  const renamedTypes = fs.readFileSync(path.join(root, 'types.ts'), 'utf8').replaceAll("'wide'", "'expanded'");
  const renamedUsage = usage.replaceAll("'wide'", "'expanded'");
  await request('update', { uri: pathToFileURL(path.join(root, 'types.ts')).href, text: renamedTypes, version: 3 });
  await request('update', { uri: pathToFileURL(usagePath).href, text: renamedUsage, version: 3 });
  const secondRename = await request('renamePlan', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 2, character: 25 }, text: renamedUsage, clientVersion: 3, newValue: 'panoramic' });
  assert.equal(secondRename.oldValue, 'expanded');
  assert.equal(secondRename.targets.length, 4);
  await request('update', { uri: pathToFileURL(path.join(root, 'types.ts')).href, text: fs.readFileSync(path.join(root, 'types.ts'), 'utf8'), version: 4 });
  await request('update', { uri: pathToFileURL(usagePath).href, text: usage, version: 4 });
  const document = await request('documentUnions', { textDocument: { uri: pathToFileURL(path.join(root, 'types.ts')).href } });
  assert(document.literals.some(literal => literal.kind === 'declaration' && literal.currentValue === 'wide'));
  assert.equal(document.literals.find(literal => literal.kind === 'declaration' && literal.currentValue === 'wide').hasUsages, true);
  assert.equal(document.literals.find(literal => literal.kind === 'declaration' && literal.currentValue === 'normal').hasUsages, false);
  const changed = usage.replace("toastStyle: 'wide'", "toastStyle: 'normal'");
  const changedDocument = await request('documentUnions', { textDocument: { uri: pathToFileURL(usagePath).href }, text: changed, clientVersion: 2 });
  assert.equal(changedDocument.clientVersion, 2);
  assert(changedDocument.literals.some(literal => literal.kind === 'usage' && literal.currentValue === 'normal'));
  const changedTarget = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 2, character: 25 }, text: changed, clientVersion: 2 });
  assert.equal(changedTarget.currentValue, 'normal');
  const ordinary = await request('resolveLiteral', { textDocument: { uri: pathToFileURL(usagePath).href }, position: { line: 3, character: 20 } });
  assert.equal(ordinary, null);
  child.kill(); fs.rmSync(root, { recursive: true, force: true });
})().catch(error => { child.kill(); fs.rmSync(root, { recursive: true, force: true }); console.error(error); process.exitCode = 1; });
