[package]
name = "typebreeze-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "typebreeze"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
typebreeze-protocol = { path = "../typebreeze-protocol" }
url.workspace = true
